site_name: CloudTAK Documentation
site_url: https://cloudtak.io
site_description: Official documentation for CloudTAK

theme:
  name: material
  custom_dir: overrides # Point to your custom template directory
  palette:
    # Set the dark mode by default
    scheme: slate
    primary: indigo # Primary color for links, etc.
    accent: purple # Accent color
  font:
    text: Inter
    code: Fira Code # A good monospace font for code blocks
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy

# Extra CSS to apply custom styles
extra_css:
  - extra.css

# Plugins (optional, but recommended for search)
plugins:
  - search

# Navigation structure
nav:
  - Home: docs.md

# Markdown extensions (optional, but enhances content)
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list
  - md_in_html

