site_name: CloudTAK Documentation
site_url: https://cloudtak.io/docs/
repo_name: CloudTAK-Docs
repo_url: https://github.com/dfpc-coe/CloudTAK-Docs
site_description: Official documentation for CloudTAK

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: indigo
    accent: purple
  font:
    text: Inter
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy

extra_css:
  - extra.css

plugins:
  - search

# Navigation structure
nav:
  - Home: docs.md
  - Deploy:
      - Home: deploy.md
  - Develop:
      - Home: develop.md
  - User Guide:
      - Home: user.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list
  - md_in_html

